Repository n-paukov/swengine, pull requests merged in 2020-09, with the labels that each got.

#58 [physics][game] Physics character controller
  sources/Engine/Exceptions/exceptions.h
  sources/Engine/Modules/Application/BaseGameApplication.cpp
  sources/Engine/Modules/ECS/GameObject.h
  sources/Engine/Modules/ECS/GameSystem.cpp
  sources/Engine/Modules/ECS/GameSystem.h
  sources/Engine/Modules/ECS/GameSystemsGroup.cpp
  sources/Engine/Modules/ECS/GameSystemsGroup.h
  sources/Engine/Modules/ECS/GameWorld.cpp
  sources/Engine/Modules/ECS/GameWorld.h
  sources/Engine/Modules/Graphics/GraphicsSystem/Animation/AnimationStatesMachine.cpp
  sources/Engine/Modules/Graphics/GraphicsSystem/GeometryCullingSystem.cpp
  sources/Engine/Modules/Graphics/GraphicsSystem/MeshRendererComponent.cpp
  sources/Engine/Modules/Graphics/GraphicsSystem/MeshRendererComponent.h
  sources/Engine/Modules/Math/geometry.cpp
  sources/Engine/Modules/Math/geometry.h
  sources/Engine/Modules/Physics/BaseBackend/KinematicCharacterComponentBackend.h
  sources/Engine/Modules/Physics/BaseBackend/PhysicsSystemBackend.h
  sources/Engine/Modules/Physics/BaseBackend/RigidBodyComponentBackend.h
  sources/Engine/Modules/Physics/BulletBackend/BulletCollisionDispatcher.h
  sources/Engine/Modules/Physics/BulletBackend/BulletCollisionShapes.h
  sources/Engine/Modules/Physics/BulletBackend/BulletDebugPainter.cpp
  sources/Engine/Modules/Physics/BulletBackend/BulletDebugPainter.h
  sources/Engine/Modules/Physics/BulletBackend/BulletHelpers.h
  sources/Engine/Modules/Physics/BulletBackend/BulletKinematicCharacterComponent.cpp
  sources/Engine/Modules/Physics/BulletBackend/BulletKinematicCharacterComponent.h
  sources/Engine/Modules/Physics/BulletBackend/BulletKinematicCharacterController.cpp
  sources/Engine/Modules/Physics/BulletBackend/BulletKinematicCharacterController.h
  sources/Engine/Modules/Physics/BulletBackend/BulletMotionState.cpp
  sources/Engine/Modules/Physics/BulletBackend/BulletMotionState.h
  sources/Engine/Modules/Physics/BulletBackend/BulletPhysicsSystemBackend.cpp
  sources/Engine/Modules/Physics/BulletBackend/BulletPhysicsSystemBackend.h
  sources/Engine/Modules/Physics/BulletBackend/BulletRigidBodyComponent.cpp
  sources/Engine/Modules/Physics/BulletBackend/BulletRigidBodyComponent.h
  sources/Engine/Modules/Physics/BulletBackend/BulletUtils.cpp
  sources/Engine/Modules/Physics/BulletBackend/BulletUtils.h
  sources/Engine/Modules/Physics/CollisionShapesFactory.h
  sources/Engine/Modules/Physics/KinematicCharacterComponent.cpp
  sources/Engine/Modules/Physics/KinematicCharacterComponent.h
  sources/Engine/Modules/Physics/PhysicsBackendFactory.cpp
  sources/Engine/Modules/Physics/PhysicsBackendFactory.h
  sources/Engine/Modules/Physics/PhysicsCollisions.h
  sources/Engine/Modules/Physics/PhysicsSystem.cpp
  sources/Engine/Modules/Physics/PhysicsSystem.h
  sources/Engine/Modules/Physics/RigidBodyComponent.cpp
  sources/Engine/Modules/Physics/RigidBodyComponent.h
  sources/Engine/precompiled.h
  sources/Game/Game/GameLevel.cpp
  sources/Game/Game/PlayerComponent.cpp
  sources/Game/Game/PlayerComponent.h
  sources/Game/Game/PlayerControlSystem.cpp
  sources/Game/Game/PlayerControlSystem.h
  sources/Game/Game/Screens/GameScreen.cpp
  sources/Tests/tests/physics/rigidBodyCollisions.cpp
  sources/Tests/tests/physics/rigidBodyInitialization.cpp
Labels: Game, Graphics subsystem, Physics subsystem

#62 [audio] Missing audio clip resource loader
  sources/Engine/Modules/Audio/Resources/AudioClipResource.cpp
  sources/Engine/Modules/Audio/Resources/AudioClipResource.h
Labels: Bug, sound system

#60 [tests] Add test for point of intersection of 3 planes and rename tests
  sources/Tests/tests/graphics/animation.cpp
  sources/Tests/tests/graphics/animationClips.cpp
  sources/Tests/tests/graphics/animationStateMachine.cpp
  sources/Tests/tests/math/collidersRestoring.cpp
  sources/Tests/tests/math/geometry.cpp
  sources/Tests/tests/math/plane.cpp
  sources/Tests/tests/math/transform.cpp
Labels: Testing

#67 [tests] Update for levels management test after ECS optimization
  sources/Tests/tests/levelsManagement/levelsManagement.cpp
Labels: Code

#72 Dialogues system
  sources/Engine/Modules/Application/BaseGameApplication.cpp
  sources/Engine/Modules/Application/BaseGameApplication.h
  sources/Engine/Modules/Audio/AudioSystem.cpp
  sources/Engine/Modules/Audio/AudioSystem.h
  sources/Engine/Modules/ECS/ECS.cpp
  sources/Engine/Modules/ECS/EventsListener.h
  sources/Engine/Modules/ECS/GameWorld.h
  sources/Engine/Modules/Graphics/GUI/GUISystem.cpp
  sources/Engine/Modules/Graphics/GUI/GUISystem.h
  sources/Engine/Modules/Graphics/GUI/GUIWidget.cpp
  sources/Engine/Modules/Graphics/GUI/GUIWidget.h
  sources/Engine/Modules/Graphics/GraphicsSystem/GraphicsSceneManagementSystem.cpp
  sources/Engine/Modules/Graphics/GraphicsSystem/GraphicsSceneManagementSystem.h
  sources/Engine/Modules/Graphics/GraphicsSystem/RenderingSystemsPipeline.cpp
  sources/Engine/Modules/Graphics/OpenGL/GLGraphicsContext.cpp
  sources/Engine/Modules/Graphics/OpenGL/GLGraphicsContext.h
  sources/Engine/Modules/Graphics/OpenGL/GLMaterial.cpp
  sources/Engine/Modules/Graphics/OpenGL/GLMaterial.h
  sources/Engine/Modules/LevelsManagement/GameObjectsLoader.cpp
  sources/Engine/Modules/Physics/BulletBackend/BulletPhysicsSystemBackend.cpp
  sources/Engine/Modules/Physics/BulletBackend/BulletPhysicsSystemBackend.h
  sources/Engine/Utility/containers.cpp
  sources/Engine/Utility/containers.h
  sources/Engine/Utility/files.cpp
  sources/Engine/Utility/files.h
  sources/Engine/Utility/numbers.cpp
  sources/Engine/Utility/numbers.h
  sources/Game/Core/GameApplication.cpp
  sources/Game/Core/GameApplication.h
  sources/Game/Game/ComponentsLoader/GameComponentsLoader.cpp
  sources/Game/Game/ComponentsLoader/GameComponentsLoader.h
  sources/Game/Game/Dynamic/ActorComponent.cpp
  sources/Game/Game/Dynamic/ActorComponent.h
  sources/Game/Game/Dynamic/Dialogue.cpp
  sources/Game/Game/Dynamic/Dialogue.h
  sources/Game/Game/Dynamic/DialoguesManager.cpp
  sources/Game/Game/Dynamic/DialoguesManager.h
  sources/Game/Game/Dynamic/DialoguesUI.cpp
  sources/Game/Game/Dynamic/DialoguesUI.h
  sources/Game/Game/Dynamic/InteractiveObjectComponent.cpp
  sources/Game/Game/Dynamic/InteractiveObjectComponent.h
  sources/Game/Game/Dynamic/InteractiveObjectsControlSystem.cpp
  sources/Game/Game/Dynamic/InteractiveObjectsControlSystem.h
  sources/Game/Game/FreeCameraControlSystem.cpp
  sources/Game/Game/FreeCameraControlSystem.h
  sources/Game/Game/Game.cpp
  sources/Game/Game/Game.h
  sources/Game/Game/Inventory/InventoryControlSystem.cpp
  sources/Game/Game/Inventory/InventoryControlSystem.h
  sources/Game/Game/PlayerControlSystem.cpp
  sources/Game/Game/PlayerControlSystem.h
  sources/Game/Game/Screens/GameScreen.cpp
  sources/Game/Game/Screens/GameScreen.h
  sources/Game/Game/Screens/MainMenuScreen.cpp
  sources/Game/Game/Screens/MainMenuScreen.h
  sources/Game/main.cpp
  sources/Tests/CMakeLists.txt
  sources/Tests/tests/game/dialogues.cpp
Labels: Game, New functionality

#73 Fix for ECS tests building
  sources/Tests/tests/ECS/ecs.cpp
Labels: Bug

#74 Tests for iteration over game objects
  sources/Tests/tests/ECS/ecs.cpp
Labels: Game, Testing
